[build]
  command = "npm run build:prod"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  NPM_FLAGS = "--production=false"

# Development/Preview Server Configuration
[dev]
  command = "npm run dev:preview"
  targetPort = 3000
  port = 8888
  publish = "dist"
  autoLaunch = true
  framework = "#static"

# Alternative dev configuration for different scenarios
[context.dev]
  command = "npm run dev:preview"

# Build contexts
[context.production]
  command = "npm run build:prod"
  
[context.deploy-preview]
  command = "npm run build:staging"
  
[context.branch-deploy]
  command = "npm run build:staging"

# Headers for all contexts
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
